### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by thnkinbtfly** [FasterDecoding/TEAL#1]
Hi! Thanks for this amazing work!

I'm having hard time to reproduce the Table 6 in your paper with this code.

What I have done is-- I ran `grab_acts.py` and copied something similar to https://github.com/FasterDecoding/TEAL/blob/9f7e408d56134573ba4f97cbdb2ad4a20845e627/teal/ppl_test.py#L16-L40
https://github.com/FasterDecoding/TEAL/blob/9f7e408d56134573ba4f97cbdb2ad4a20845e627/teal/ppl_test.py#L64
in `lm-evaluation-harness`.

Could you provide more details how to reproduce it? (For example, on which corpus the histograms are collected, with which number of samples, etc)

**Comment by thnkinbtfly** [comment]
Also, where can I find the greedy algorithm to generate the `lookup` folder?

**Comment by chromecast56** [comment]
Hi! I'm working on including the greedy algorithm, and will expect to have that very soon. You may be able to reproduce the results in Table 4 for the uniform case right now.

The histograms are collected from alpaca, 10 samples of sequence length 2048

**Comment by thnkinbtfly** [comment]
Ah, Thanks!

**Comment by chromecast56** [comment]
I've pushed a serial version of the greedy algorithm for now (having trouble parallelizing over GPUs cleanly), and have also updated the `models` folder to include the associated `lookup` folders.

To load block-wise greedy sparsities, you can do the following:

```
        greedy_path = os.path.join(args.teal_path, "lookup")
        model.load_greedy_sparsities(greedy_path, args.sparsity)
```


Let me know if you still have any issues!
