### ISSUE TITLE
how to make the histogram files?

### ISSUE THREAD

**Issue by milktea888** [FasterDecoding/TEAL#3]
Hello, may I know if you release the histogram files making codes? Thanks!

**Comment by chromecast56** [comment]
it should be in the "accuracy" section of the README:

1. Construct histograms for threshold calibration (scripts/grab_acts.bash):

```
CUDA_VISIBLE_DEVICES=0 python teal/grab_acts.py \  
  --model_name meta-llama/Llama-2-7b-hf \ 
  --output_path $OUTPUT_PATH
```


You may additionally construct block-wise greedy lookup tables:

```
CUDA_VISIBLE_DEVICES=0 python teal/greedyopt.py \
  --model_name meta-llama/Llama-2-7b-hf \
  --model_type Llama-2-7B \
  --teal_path $OUTPUT_PATH \
  --target_sparsity 0.9 \
  --base_step_size 0.05 \
  --last_fraction 0.25
```

**Comment by milktea888** [comment]
thank you so much! I'll take a try.
