### ISSUE TITLE
why the ppl  test result do not align with paper ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [FasterDecoding/TEAL#4]
Hi author,

     i run the code follow the steps which you write on user guide. why i get ppl result do not align with paper ??
![image](https://github.com/user-attachments/assets/fd3e76d8-8b35-4e2d-bb4c-4e5b93ce42b0)

![image](https://github.com/user-attachments/assets/ed06203a-db2f-4719-89ea-2fe667986c38)

![image](https://github.com/user-attachments/assets/3c4a42f2-d8a7-448c-ad25-0826f08c4bf2)

**Comment by chromecast56** [comment]
The `ppl_test` currently uses Alpaca, you may switch it to wikitext for evaluation on wikitext. There may be slight variation (we use a subset for convenience) but you should see comparable results.
