### ISSUE TITLE
histogram

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [FasterDecoding/TEAL#6]
Very interesting work. I am confused about the purpose of making histogram. Can you explain the specific relationship with the threshold? In addition, can you provide the histogram visualization code about the histogram.pt file?

**Comment by LiuJinzhe-Keepgoing** [comment]
I don't understand what the function of grab_acts is. Thank you for your explanation

**Comment by chromecast56** [comment]
Hi! See [this](https://github.com/FasterDecoding/TEAL/issues/8#issuecomment-2365445300) for code to visualize the histograms. Histograms are needed to set thresholds to their correct values -- if you want to threshold 50% of a hidden state's activations to 0, based on absolute value, you need some knowledge of the underlying distribution of activations, which histograms provide.
