### ISSUE TITLE
Which code can support EleutherAI LM Harness test ?

### ISSUE THREAD

**Issue by CarlHuangNuc** [FasterDecoding/TEAL#7]
Hi Author,

          Could you share some code which can help our to reproduce  this table data ?

![image](https://github.com/user-attachments/assets/d308a7d8-86e4-4dc4-825b-0e6c339ad7bf)

**Comment by chromecast56** [comment]
For LM Eval Harness, you can register the sparse models in AutoModel in `lm_eval/models/huggingface.py`:
```
import sys
sys.path.append("$HOME_PATH/TEAL")
from sparsedoping.model import LlamaSparseForCausalLM, LlamaSparseConfig
from sparsedoping.model import MistralSparseForCausalLM, MistralSparseConfig
from transformers import AutoConfig, AutoModelForCausalLM
AutoConfig.register("llama_sparse", LlamaSparseConfig)
AutoConfig.register("mistral_sparse", MistralSparseConfig)
AutoModelForCausalLM.register(LlamaSparseConfig, LlamaSparseForCausalLM)
AutoModelForCausalLM.register(MistralSparseConfig, MistralSparseForCausalLM)
```

Models must be of type `llama_sparse` or `mistral_sparse`. An easy way to do this is to add the following at the end of `eval_ppl.py`:

```
model.save_pretrained("path/to/model")
tokenizer.save_pretrained("path/to/model")
```
